format_version: 3

pipelines:
  test_pipeline:
    group: Test-Group
    label_template: '${COUNT}'

    materials:
      git:
        url: https://github.com/SumanGupta24x7/test_pipeline
        branch: master

    stages:
      - hello_stage:
          jobs:
            - hello_job:
                tasks:
                  - exec:
                      command: echo "Hello world"
